<a href="https://colab.research.google.com/github/Muluken1Walle/NumpyMiniProject/blob/main/MiniProject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
data_file='makeSenseOfCensus.csv'


In [3]:
import numpy as np

In [6]:
data= np.genfromtxt(data_file, delimiter=',', skip_header=1)
print("\ndata:\n\n",data)


data:

 [[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]


In [9]:
print("\ntype of data\n\n", type(data))


type of data

 <class 'numpy.ndarray'>


In [13]:
new_record= [[50,9,4,1,0,0,40,0]]
print(new_record)

[[50, 9, 4, 1, 0, 0, 40, 0]]


In [14]:
data1=np.concatenate((data,new_record), axis=0)
print(data1)

[[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]
 [50.  9.  4. ...  0. 40.  0.]]


In [17]:
age = data1[:,0]
print(age)

[39. 50. 38. ... 40. 39. 50.]


In [20]:
max_age= age.max()
max_age

90.0

In [22]:
min_age = age.min()
min_age

17.0

In [24]:
age_mean= age.mean()
age_mean

38.06293706293706

In [25]:
age_std= age.std()
age_std

13.341478176165857

In [27]:
race = data1[:,2]
print(race)

[4. 4. 4. ... 4. 4. 4.]


In [29]:
race_0 = race[race == 0]
race_1= race[race==1]
race_2 = race[race==2]
race_3 = race[race==3]
race_4= race[race==4]
print(race_4)

[4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.
 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.

In [31]:
len_0 = len(race_0)
len_1= len(race_1)
len_2 =len(race_2)
len_3 = len(race_3)
len_4 = len(race_4)
print(len_0,len_1,len_2,len_3,len_4)

10 27 110 6 848


In [33]:
list1 = [len_0,len_1,len_2,len_3,len_4]
len_arr = np.array(list1)
print('Minimum number of citizens in a race is',len_arr.min())

Minimum number of citizens in a race is 6


In [34]:
minority_race = 3
print('The belong to minority is Race',minority_race)

The belong to minority is Race 3


In [35]:
senior_citizens = age[age>60]
print(senior_citizens)


[79. 67. 76. 61. 70. 64. 71. 68. 66. 64. 90. 66. 75. 65. 64. 61. 65. 77.
 62. 76. 63. 66. 67. 65. 62. 63. 80. 67. 63. 72. 62. 74. 67. 72. 69. 65.
 65. 71. 70. 66. 65. 61. 61. 68. 64. 64. 62. 73. 72. 63. 62. 61. 71. 63.
 63. 67. 81. 64. 67. 78. 63.]


In [36]:
working_hours = data1[:,6]
working_hours_sum =  np.sum(working_hours[age>60])
print('Toatl working hour of senior citizens',working_hours_sum)

Toatl working hour of senior citizens 1917.0


In [37]:
senior_citizens_len = len(senior_citizens)
print(senior_citizens_len)

61


In [38]:
avg_working_hours= working_hours_sum/senior_citizens_len
print(avg_working_hours)

31.42622950819672


In [41]:
if avg_working_hours <=25:
  print('the gov policy is followd ')
else:
  print('the gov is not followd')


the gov is not followd


In [42]:
print(avg_working_hours)

31.42622950819672


In [43]:
education= data1[:,1]
high = education[education>10]
low = education[education<10]
print(high)

[13. 13. 13. 14. 14. 13. 13. 13. 12. 11. 14. 16. 13. 12. 13. 12. 13. 13.
 13. 14. 11. 11. 15. 13. 11. 13. 16. 13. 13. 12. 13. 14. 16. 11. 13. 16.
 12. 14. 13. 14. 13. 15. 11. 13. 13. 13. 13. 12. 12. 13. 12. 14. 11. 11.
 13. 13. 13. 14. 14. 12. 14. 11. 13. 13. 13. 13. 13. 14. 16. 13. 13. 14.
 14. 14. 13. 13. 13. 12. 13. 13. 11. 15. 13. 14. 13. 12. 12. 15. 13. 11.
 13. 13. 14. 14. 13. 12. 13. 14. 15. 13. 13. 13. 13. 13. 14. 13. 12. 12.
 12. 13. 14. 13. 14. 11. 13. 11. 14. 12. 11. 13. 11. 12. 13. 13. 13. 13.
 11. 14. 13. 13. 12. 13. 11. 14. 13. 12. 13. 13. 13. 13. 11. 14. 16. 13.
 14. 14. 13. 12. 14. 13. 12. 11. 12. 13. 13. 14. 13. 11. 13. 12. 13. 13.
 13. 12. 13. 13. 13. 11. 11. 11. 13. 13. 13. 14. 12. 15. 11. 13. 16. 11.
 13. 13. 13. 14. 14. 11. 16. 13. 12. 13. 13. 13. 13. 13. 15. 13. 13. 12.
 14. 14. 13. 13. 13. 15. 13. 11. 13. 13. 13. 13. 16. 16. 13. 16. 14. 14.
 12. 13. 11. 13. 14. 13. 12. 14. 14. 13. 13. 13. 16. 13. 13. 13. 11. 13.
 13. 13. 13. 13. 11. 11. 13. 13. 14. 11. 13. 13. 13

In [44]:
print(low)

[9. 7. 5. 9. 4. 9. 9. 7. 9. 5. 7. 9. 9. 9. 9. 7. 9. 5. 9. 9. 9. 9. 9. 3.
 9. 9. 4. 9. 9. 9. 9. 6. 7. 4. 9. 9. 9. 9. 9. 9. 5. 9. 9. 9. 9. 6. 7. 9.
 9. 9. 9. 5. 9. 9. 9. 9. 9. 9. 9. 9. 7. 9. 9. 9. 9. 9. 2. 9. 9. 7. 9. 9.
 9. 9. 9. 9. 4. 9. 3. 9. 9. 9. 7. 9. 9. 7. 9. 9. 9. 4. 6. 2. 9. 9. 1. 9.
 6. 9. 9. 7. 9. 9. 9. 9. 9. 9. 9. 9. 6. 9. 9. 9. 4. 9. 7. 7. 9. 9. 9. 5.
 9. 9. 9. 4. 9. 9. 9. 9. 9. 9. 9. 3. 9. 9. 9. 7. 9. 9. 9. 6. 9. 3. 9. 9.
 9. 9. 9. 7. 9. 7. 9. 7. 9. 5. 6. 9. 9. 9. 7. 9. 9. 9. 9. 9. 3. 9. 9. 9.
 9. 9. 9. 4. 9. 9. 9. 8. 2. 7. 7. 9. 7. 9. 6. 9. 9. 9. 9. 7. 9. 9. 9. 5.
 9. 9. 9. 7. 9. 9. 9. 9. 9. 9. 2. 9. 9. 9. 9. 5. 6. 9. 9. 8. 2. 9. 9. 9.
 9. 9. 3. 9. 9. 9. 9. 9. 3. 9. 9. 9. 7. 9. 9. 8. 2. 9. 9. 9. 6. 9. 9. 7.
 9. 7. 9. 9. 9. 7. 9. 9. 4. 9. 9. 9. 7. 8. 9. 9. 9. 7. 6. 9. 9. 4. 9. 4.
 5. 9. 9. 9. 6. 9. 9. 9. 9. 9. 7. 5. 5. 9. 9. 9. 6. 9. 9. 3. 9. 9. 9. 9.
 9. 9. 9. 5. 9. 4. 9. 8. 9. 7. 5. 7. 7. 9. 9. 8. 9. 9. 9. 9. 7. 9. 4. 9.
 9. 8. 9. 7. 9. 9. 9. 9. 9. 9. 9. 9. 7. 9. 9. 8. 9.

In [48]:
income = data1[:,7]
avg_pay_high = np.mean(income[education>10])
avg_pay_low = np.mean(income[education<=10])
print("Average pay for high",avg_pay_high,"\nAverage pay for low", avg_pay_low)

Average pay for high 0.42813455657492355 
Average pay for low 0.13649851632047477
